name: Update Live Streams

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小時執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-live-streams:
    runs-on: ubuntu-latest
    steps:
      - name: 設置 Git 使用者資訊
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: 檢查出 Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 確保推送權限
          fetch-depth: 0  # 確保完整 history，以便 rebase

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 安裝必要的 Python 套件（如果有）
        run: |
          pip install -r requirements.txt || echo "No dependencies needed."

      - name: 執行爬蟲
        run: python script.py

      - name: 檢查是否有變更
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: 提交變更
        run: |
          git commit -m "Auto-update live streams"
          git pull --rebase origin main  # 先拉取最新變更，避免衝突
          git push origin main  # 推送變更
